"""init

Revision ID: 3da47ceac768 
Create Date: 2017-02-13 16:47:16.371746

"""

# revision identifiers, used by Alembic.
revision = '3da47ceac768'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provenance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataset', sa.VARCHAR(length=50), nullable=False),
    sa.Column('matlab_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('spm_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('spm_revision', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fn_called', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fn_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('others', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=200), nullable=True),
    sa.Column('manufacturer_model_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('institution_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('slice_thickness', sa.DECIMAL(), nullable=True),
    sa.Column('repetition_time', sa.DECIMAL(), nullable=True),
    sa.Column('echo_time', sa.DECIMAL(), nullable=True),
    sa.Column('echo_number', sa.INTEGER(), nullable=True),
    sa.Column('number_of_phase_encoding_steps', sa.INTEGER(), nullable=True),
    sa.Column('percent_phase_field_of_view', sa.DECIMAL(), nullable=True),
    sa.Column('pixel_bandwidth', sa.INTEGER(), nullable=True),
    sa.Column('flip_angle', sa.DECIMAL(), nullable=True),
    sa.Column('rows', sa.INTEGER(), nullable=True),
    sa.Column('columns', sa.INTEGER(), nullable=True),
    sa.Column('magnetic_field_strength', sa.DECIMAL(), nullable=True),
    sa.Column('space_between_slices', sa.DECIMAL(), nullable=True),
    sa.Column('echo_train_length', sa.INTEGER(), nullable=True),
    sa.Column('percent_sampling', sa.DECIMAL(), nullable=True),
    sa.Column('pixel_spacing_0', sa.DECIMAL(), nullable=True),
    sa.Column('pixel_spacing_1', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=True),
    sa.Column('handedness', sa.Enum('left', 'right', 'ambidexter', name='handedness'), nullable=True),
    sa.Column('birthdate', sa.DATE(), nullable=True),
    sa.Column('age', sa.DECIMAL(), nullable=True),
    sa.Column('provenance_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'provenance_id')
    )
    op.create_table('processing_step',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('previous_step_id', sa.INTEGER(), nullable=True),
    sa.Column('provenance_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('execution_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['previous_step_id'], ['processing_step.id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('role', sa.Enum('C', 'P', 'IC', name='scan_role'), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('participant_id', sa.INTEGER(), nullable=False),
    sa.Column('provenance_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'provenance_id')
    )
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('scan_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scan_id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('sequence_type_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_type_id'], ['sequence_type.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'session_id')
    )
    op.create_table('repetition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('sequence_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'sequence_id')
    )
    op.create_table('data_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('repetition_id', sa.INTEGER(), nullable=True),
    sa.Column('processing_step_id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('result_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('output_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_copy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['processing_step_id'], ['processing_step.id'], ),
    sa.ForeignKeyConstraint(['repetition_id'], ['repetition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_file')
    op.drop_table('repetition')
    op.drop_table('sequence')
    op.drop_table('session')
    op.drop_table('scan')
    op.drop_table('processing_step')
    op.drop_table('participant')
    op.drop_table('sequence_type')
    op.drop_table('provenance')
    # ### end Alembic commands ###
