"""add patient_age column to visit table

Revision ID: 6dce85f8104f
Revises: 4cdf45858e47
Create Date: 2017-03-08 15:07:00.551667

"""

# revision identifiers, used by Alembic.
revision = '6dce85f8104f'
down_revision = '4cdf45858e47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('patient_age', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'patient_age')
    # ### end Alembic commands ###
